//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelReservationSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class room
    {
        public int id { get; set; }
        public string kind { get; set; }
        public string r_view { get; set; }
        public Nullable<int> bedNo { get; set; }
        public Nullable<double> price { get; set; }
    }
}
